# CodiesVibe Backend Development Environment
# Docker Compose configuration for backend services with gateway
# Use: docker-compose -f docker-compose.backend.yml up



services:
  # API Gateway - Development overrides
  gateway:
    extends:
      file: docker-compose/services/docker-compose.gateway.yml
      service: gateway
    ports:
      - "4000:4000"  # External gateway port
    volumes:
      # Log volume for debugging
      - gateway_logs:/var/log/nginx

  # NestJS API Service - Development overrides
  nestjs-api:
    extends:
      file: docker-compose/services/docker-compose.nestjs.yml
      service: nestjs-api
    build:
      target: development  # Development build target
    ports:
      - "4001:4001"  # External port mapping for development access
    expose:
      - "4001"  # Internal port only - accessed through gateway
    volumes:
      # Mount source code for development hot-reload
      - ./backend/nestjs-api/src:/app/src
      - ./backend/shared:/app/shared
      # Mount package.json for hot reload
      - ./backend/nestjs-api/package.json:/app/package.json
      # Log volume
      - nestjs_logs:/app/logs
    environment:
      - NODE_ENV=development
      - PORT=4001
      # GitHub OAuth (development)
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID:-your_github_client_id}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET:-your_github_client_secret}
      - GITHUB_CALLBACK_URL=http://localhost:4000/api/auth/github/callback
    # Infrastructure dependencies come from docker-compose.infra.yml
    depends_on: []



  # Fastify API Service - Development overrides
  fastify-api:
    extends:
      file: docker-compose/services/docker-compose.fastify.yml
      service: fastify-api
    expose:
      - "4002"  # Internal port only - accessed through gateway or NestJS
    ports:
      - "4002:4002"  # Exposed for direct development access
    volumes:
      # Mount source code for development hot-reload
      - ./backend/fastify-api:/app
      - /app/node_modules  # Anonymous volume for node_modules
      # Mount shared types
      - ./backend/shared:/app/shared
      # Log volume
      - fastify_logs:/app/logs
    environment:
      - NODE_ENV=development
      - PORT=4002
      # MCP Server Configuration
      - MCP_SERVER_URL=http://codiesvibe-mcp-server:3001
      # Ollama Configuration
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=llama3.2
      # CORS Configuration
      - CORS_ORIGIN=http://localhost:3000
    # Infrastructure dependencies come from docker-compose.infra.yml
    depends_on: []

# Named volumes for application logs only
volumes:
  gateway_logs:
    driver: local
  nestjs_logs:
    driver: local
  fastify_logs:
    driver: local

# External network configuration (created by docker-compose.infra.yml)
networks:
  codiesvibe-network:
    external: true
    name: codiesvibe-network