# Gateway Service Base Definition
# Reusable Gateway service configuration for all environments

services:
  gateway:
    build:
      context: ../../backend/gateway
      dockerfile: Dockerfile.gateway
      args:
        - BUILD_DATE=${BUILD_DATE:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
        - GIT_COMMIT=${GIT_COMMIT:-$(git rev-parse --short HEAD)}
        - VERSION=${VERSION:-latest}
    networks:
      - codiesvibe-network
    depends_on:
      nestjs-api:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3
    environment:
      - NGINX_WORKER_PROCESSES=auto
      - NGINX_WORKER_CONNECTIONS=1024
      # Service name configuration for nginx upstream
      - NESTJS_SERVICE_HOST=${NESTJS_SERVICE_HOST:-codiesvibe-nestjs-api-1}
      - NESTJS_SERVICE_PORT=${NESTJS_SERVICE_PORT:-4001}
      - FASTIFY_SERVICE_HOST=${FASTIFY_SERVICE_HOST:-codiesvibe-fastify-api-1}
      - FASTIFY_SERVICE_PORT=${FASTIFY_SERVICE_PORT:-4002}

networks:
  codiesvibe-network:
    driver: bridge
    name: codiesvibe-network