# Prometheus Extended Configuration for CodiesVibe
# Extended monitoring with application-specific metrics
# Integrates with infrastructure Prometheus (port 9090) using offset port 9091

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'codiesvibe-extended'
    environment: 'extended'

# Rule files for alerting
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Self-monitoring
  - job_name: 'prometheus-extended'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # Application Metrics Exporter (custom)
  - job_name: 'app-metrics'
    static_configs:
      - targets: ['app-metrics-exporter:8080']
    scrape_interval: 30s
    metrics_path: /metrics

  # CodiesVibe Backend Application Metrics
  - job_name: 'codiesvibe-backend'
    static_configs:
      - targets: ['backend:4000']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # Infrastructure Prometheus (federation)
  - job_name: 'infrastructure-prometheus'
    static_configs:
      - targets: ['prometheus:9090']
    metrics_path: /federate
    params:
      'match[]':
        - '{job=~"mongodb|redis|grafana|loki"}'
    scrape_interval: 30s
    honor_labels: true

  # MongoDB metrics (if mongodb-exporter is available)
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis metrics (if redis-exporter is available)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Nginx metrics (if nginx-prometheus-exporter is available)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Docker daemon metrics (if available)
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true

# Web configuration
web:
  enable-lifecycle: true
  enable-admin-api: true
  external-url: http://localhost:9091
  route-prefix: /